Exit early if blaze build fails
Bug: 64846738
Test: manual on walleye
Change-Id: I38b15b63891cdd6691dc60c8aa935cdafe26ede4

diff --git a/prebuilts/update-gcam-from-google3 b/prebuilts/update-gcam-from-google3
--- a/prebuilts/update-gcam-from-google3
+++ b/prebuilts/update-gcam-from-google3
@@ -122,6 +122,10 @@ pushd ${GOOGLE3_PATH}
 # Generate PCG
 rm -rf ${TMP_PCG_FULL_PATH}
 GLOG_v=-2 ${GOOGLE3_PCG_GEN_SH} --pcg_output_dir=${TMP_PCG_FULL_PATH}
+if [ $? -ne 0 ]; then
+  echo "Error: ${GOOGLE3_PCG_GEN_SH} returned non-zero"
+  exit 1
+fi
 
 # Build libgcam
 blaze build \
